name = "Dopetrope"
license = "Creative Commons"
licenselink = "https://github.com/curttimson/hugo-theme-dopetrope/blob/master/LICENSE.md"
description = "An elegant open-source and mobile-first theme"
homepage = "https://html5up.net/uploads/demos/dopetrope/index.html"
tags = ["blog", "html5up"]
features = ["blog"]
min_version = 0.19

[author]
    name = "Curtis Timson"
    homepage = "https://curtistimson.co.uk/"

# If porting an existing theme
[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"
    repo = "https://html5up.net/dopetrope"